apps/about_me/urls.py
# -*- coding: utf-8 -*-
# author: 'boliang'
# date: 2017/10/22 21:03


from django.conf.urls import url

from .views import AboutView


urlpatterns = [
    url(r'^$', AboutView.as_view(), name='about')
]

apps/main/urls.py
# -*- coding: utf-8 -*-
# author: 'boliang'
# date: 2017/10/24 11:58


from django.conf.urls import url

from .views import IndexView, Ie8View


urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'ie8_error', Ie8View.as_view(), name='ie8')
]

apps/operation/urls.py
# -*- coding: utf-8 -*-
# author: 'boliang'
# date: 2017/10/22 22:21


from django.conf.urls import url

from .views import MessageView, SendCommentView, SendGoodclicksView


urlpatterns = [
    url(r'^$', MessageView.as_view(), name='message'),
    url(r'^send_message/$', MessageView.as_view(), name='send_message'),
    url(r'^send_comment/$', SendCommentView.as_view(), name='send_comment'),
    url(r'^send_good_clicks/$', SendGoodclicksView.as_view(), name='send_good_clicks')
]

apps/photos_manage/urls.py
# -*- coding: utf-8 -*-
# author: 'boliang'
# date: 2017/10/23 22:27


from django.conf.urls import url

from .views import PhotoShowView


urlpatterns = [
    url(r'^$', PhotoShowView.as_view(), name='photos')
]

boliangblog/urls.py
# -*- coding: utf-8 -*-
"""boliangblog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url, include
from DjangoUeditor import urls as DjangoUeditor_urls
from django.views.static import serve # 用于静态文件传递
import xadmin

from settings import MEDIA_ROOT

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^ueditor/', include(DjangoUeditor_urls)),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

    url(r'', include('main.urls', namespace='main')),
    url(r'^about/', include('about_me.urls', namespace='about_me')),
    url(r'^message/', include('operation.urls', namespace='operation')),
    url(r'^photos/', include('photos_manage.urls', namespace='photos')),
    url(r'^articles_manage/', include('articles_manage.urls', namespace='articles_manage'))
]

templates/about.html
{% extends 'public.html' %}

{% block title %}About Me{% endblock %}

{% block css %}
	<link rel="stylesheet" type="text/css" href="/static/css/public.css" />
	<link rel="stylesheet" type="text/css" href="/static/css/study.css" />
	<link rel="stylesheet" type="text/css" href="/static/css/about.css" />
{% endblock %}

{% block body %}

<div class="container">
				<div class="col-md-8 body-left">
					<div class="panel">
						<div class="panel-heading">
							<h1 class="text-center">About Me</h1>
						</div>
						<div class="panel-body">
							<div class="col-md-4 img-me text-center">
								<img src="/media/{{about_me.image}}" class="img-rounded" />
							</div>
							<div class="col-md-8 desc-body">
								{% autoescape off %}
								{{about_me.desc}}
								{% endautoescape %}
							</div>

						</div>
					</div>
				</div>
				<div class="col-md-4 body-right">
					<div class="jumbotron">
						<div class="panel">
							<div class="panel-heading" style="background: transparent;">
								<img src="/media/{{about_me.head_image}}" class="img-circle img center-block" />
							</div>
							<div class="panel-body">
								<ul class="list-group desc-me">
									<li class="list-group-item">
										OWNER: <span>{{about_me.name}}</span>
									</li>
									<li class="list-group-item">
										AGE: <span>{{about_me.age}}</span>
									</li>
									<li class="list-group-item">
										JOB: <span>{{about_me.job}}</span>
									</li>
									<li class="list-group-item">
										QQ: <span>{{about_me.qq}}</span>
									</li>
									<li class="list-group-item">
										HOBBIES: <span>{{about_me.hobbies}}</span>
									</li>
									<li class="list-group-item">
										MOTTO: <span>{{about_me.motto}}</span>
									</li>
								</ul>
							</div>
						</div>
						<div class="panel">
							<div class="panel-heading">
								<h3>最新文章</h3>
							</div>
							<div class="panel-body">
								<ul class="list-group panel-list">
									{% for article in articles %}
									<li class="list-group-item">
										<a class="title" href="{% url 'articles_manage:article' %}?id={{article.id}}">
											<span class="pull-left">{{article.name}}</span>
											<span class="pull-right">{{article.add_time}}</span>
										</a>
									</li>
									{% endfor %}
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>

{% endblock %}

templates/article.html
{% extends 'public.html' %}

{% block keywords %}{{article.name}},{{article.sort}} {% endblock %}

{% block desc %}{{article.name}},{{article.sort}} {% endblock %}

{% block name %}{{article.name}},{{article.sort}} {% endblock %}

{% block title %}{{article.name}}{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/css/public.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/study.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/sort.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/message.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/article.css" />
{% endblock %}

{% block js %}
    <script src="/static/js/message.js" type="text/javascript" charset="utf-8"></script>
    <script src="/static/js/goodclick.js" type="text/javascript" charset="utf-8"></script>
{% endblock %}

{% block body %}
<div class="container">
    <div class="col-md-9 body-left">
        <div class="panel">

            <div class="current-position clearfix">
                <h4 class="col-md-2 col-xs-12 text-right">当前位置</h4>
                <ul class="col-md-10 col-xs-12 btn-group">
                    {% if not_feelings %}
                    <li class="pull-left">
                        <span>——</span>
                        <a href="{% url 'articles_manage:study' %}" class="btn">study</a>
                    </li>

                    <li class="pull-left">
                        <span>——</span>
                        <a href="{% url 'articles_manage:study' %}?sort={{article_sort.id}}" class="btn">
                            {{article.sort}}
                        </a>
                    </li>
                    {% else %}
                    <li class="pull-left">
                        <span>——</span>
                        <a href="{% url 'articles_manage:feelings' %}" class="btn">
                            {{article.sort}}
                        </a>
                    </li>
                    {% endif %}
                    <li class="pull-left">
                        <span>——</span>
                        <a href="{% url 'articles_manage:article' %}?{% if not send_sort == 0 %}sort={{send_sort}}&{% endif %}id={{article.id}}" class="btn">
                            {{article.name}}
                        </a>
                    </li>
                </ul>
            </div>
            <div class="panel-body article-container">
                <div class="article-title text-center">
                    <h3 class="title">{{article.name}}</h3>
                    <small class="time"><span>Time:&nbsp;</span>{{article.add_time}}</small>
                </div>
                <div class="article-body center-block">
                    <br />
                  {% autoescape off %}
                  {{article.content}}
                  {% endautoescape %}
                </div>

                <div class="article-footer">
                    <form id="good-click-form" class="hidden">
                        {% csrf_token %}
                        <input type="text" name="goodclick" value="goodclick" />
                        <input type="submit" value="submit" />
                        <input type="text" class="hidden" value="{{article.id}}" name="article_id" />
                    </form>

                    <h3 class="text-center good-click">
                        <span class="glyphicon glyphicon-thumbs-up"></span>
                        <small>{{article.good_clicks}}</small>
                    </h3>

                    {% if not pre_article == 'None' %}
                    <a href="{% url 'articles_manage:article' %}?{% if not send_sort == 0 %}sort={{send_sort}}&{% endif %}id={{pre_article.id}}" class="pull-left">
                        上一篇:<span>{{pre_article.name}}</span>
                    </a>
                    {% endif %}

                    {% if not next_article == 'None' %}
                    <a href="{% url 'articles_manage:article' %}?{% if not send_sort == 0 %}sort={{send_sort}}&{% endif %}id={{next_article.id}}" class="pull-right">
                        下一篇:<span>{{next_article.name}}</span>
                    </a>
                    {% endif %}
                </div>

            </div>

        </div>

        <div class="panel comments-page">
            <h3>Comments</h3>

            <div class="panel-body message-list">
                <button class="btn btn-primary center-block" type="button" data-target="#send-message" data-toggle="modal" id="send-message-btn">评论一下</button>
                <ul class="media-list">
                    {% for comment in comments.object_list %}
                    <li class="media">

                        <div class="media-object col-md-2 text-right">
                            <img src="{{comment.image}}" class="img-circle" />
                            <div class="triangle pull-right">
                            </div>
                        </div>
                        <div class="col-md-10 message-body">
                            <h3 class="media-heading">{{comment.username}}:</h3>
                            <p>{{comment.message}}</p>
                            <div class="media-bottom pull-right">
                                <h4>{{comment.add_time}}</h4>
                            </div>
                        </div>

                    </li>
                    {% endfor %}
                </ul>

                <div class="row text-center">
                    <ul class="pagination">
                        {% if comments.has_previous %}
                    <li id="pre-page">
                        <a href="?{{comments.previous_page_number.querystring}}" aria-label="Previous">
                            <span aria-hidden="true">上一页</span>
                        </a>
                    </li>
                    {% endif %}

                    {% for page in comments.pages %}
                        {% if page == pre_ignore_page|add:1%}
                        <li class="pages">
                            <a href="?{% if not send_sort == 0 %}sort={{send_sort}}&{% endif %}id={{article.id}}&page={{pre_ignore_page}}">
                                ...
                            </a>
                        </li>
                        {% endif %}
                        {% if page %}
                        <li class="pages {% ifequal page comments.number %}active{% endifequal %}">
                            <a href="?{{page.querystring}}">{{page}}</a>
                        </li>
                        {% endif %}
                        {% if page|add:1 == next_ignore_page %}
                        <li class="pages">
                            <a href="?{% if not send_sort == 0 %}sort={{send_sort}}&{% endif %}id={{article.id}}&page={{next_ignore_page}}">
                                ...
                            </a>
                        </li>
                        {% endif %}
                    {% endfor %}

                    {% if comments.has_next %}
                    <li id="next-page">
                        <a href="?{{comments.next_page_number.querystring}}" aria-label="Next">
                            <span aria-hidden="true">下一页</span>
                        </a>
                    </li>
                    {% endif %}
                    </ul>
                </div>
            </div>

        </div>

    </div>
    <div class="col-md-3 body-right">
        <div class="jumbotron">
            <div class="panel">
                <div class="panel-heading">
                    <h3>Motto</h3>
                </div>
                <div class="panel-body">

                    <p class="motto">{{writing.content}}</p>
                    <footer class="pull-right">
                        <span>————</span> {{writing.from_name}}
                    </footer>

                </div>
            </div>
            <div class="panel">
                <div class="panel-heading">
                    <h3>热门标签</h3>
                </div>
                <div class="panel-body">
                    <ul class="btn-group" style="width: 100%;">
                        {% for tmp_article_sort in tmp_article_sorts %}
                        <li class="col-md-6 col-xs-6 text-center">
                            <a href="{% url 'articles_manage:study' %}?sort={{tmp_article_sort.article_sort.id}}" class="btn {{tmp_article_sort.color}}">
                                {{tmp_article_sort.article_sort.name}}
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="panel">
                <div class="panel-heading">
                    <h3>最新文章</h3>
                </div>
                <div class="panel-body">
                    <ul class="list-group panel-list">
                        {% for new_article in new_articles %}
                        <li class="list-group-item">
                            <a class="title"
                               href="{% url 'articles_manage:article' %}?id={{new_article.id}}">
                                <span class="pull-left">{{new_article.name}}</span>
                                <span class="pull-right">{{new_article.add_time}}</span>
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>

    </div>

</div>

<div class="modal fade" id="send-message">
    <div class="modal-dialog">
        <form class="modal-content" id="send-message-form">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h3 class="modal-title text-center">Comment</h3>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="head-img">选择头像</label>
                    <div class="dropdown" id="head-img">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">

                        <img src="/media/{{first_image.image}}" class="img-circle"/>
                        <input type="text" name="image" class="hidden" value="/media/{{first_image.image}}" />

                        </button>
                         <input type="text" name="from_article" class="hidden" value="{{article.id}}" />
                        <ul class="dropdown-menu text-center" aria-labelledby="dropdownMenu1">
                            {% for head_image in head_images %}
                            <li>
                                <img src="/media/{{head_image.image}}" class="img-circle center-block img-select" />
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">您的名字<span class="must-input">*必填</span></label>
                    <input type="text" id="username" placeholder="please input your name" class="form-control" name="username" />
                </div>
                <div class="form-group">
                    <label for="email">您的邮箱<span class="must-input">*必填(不公开)</span></label>
                    <input type="text" id="email" placeholder="please input your email" class="form-control" name="email" />
                </div>
                <div class="form-group">
                    <label for="address">您的网址<span class="select-input">&nbsp;选填</span></label>
                    <input type="text" id="address" placeholder="please input your address" class="form-control" name="address" />
                </div>
                <div class="form-group">
                    <label for="username">您的评论<span class="must-input">*必填</span></label>
                    <textarea id="message" name="message" rows="10" class="form-control" placeholder="please input your comment"></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" id="close-btn">关闭</button>
                <button type="reset" class="btn btn-primary" id="reset-btn">重置</button>
                <button type="button" class="btn btn-primary" id="send-btn">发送</button>
            </div>
        </form>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<input type="text" class="hidden" id="send_sort" value="{{send_sort}}" />
<input type="text" class="hidden" id="article_id" value="{{article.id}}" />
<div class="col-md-6 col-lg-push-3 text-center center-block alert-danger hidden">
    <h1>请填写好所有必填内容，谢谢!</h1>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
    $(function() {
        new MessageOperation("{% url 'operation:send_comment' %}");
        new GoodClick("{% url 'operation:send_good_clicks' %}");
    });
</script>
{% endblock %}

templates/ie8.html
<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no" />
		<title>您的浏览器版本过低</title>

		<!-- Bootstrap -->
		<link href="/static/css/bootstrap.min.css" rel="stylesheet">

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
	</head>

	<body>
		<div class="container">
			<div class="panel panel-danger" style="margin: 100px auto;">
				<div class="panel-heading">
					<h1 class="text-center">亲！ 您的浏览器版本过低哦！</h1>
				</div>
				<div class="panel-body">
					<p class="text-center">亲！ 您的浏览器版本过低哦！ 请升级下浏览器再来访问吧！！！！！</p>
				</div>
			</div>
		</div>
	</body>

</html>

templates/message.html
{% extends 'public.html' %}

{% block title %}Message{% endblock %}

{% block css %}
        <link rel="stylesheet" type="text/css" href="/static/css/public.css" />
		<link rel="stylesheet" type="text/css" href="/static/css/study.css" />
		<link rel="stylesheet" type="text/css" href="/static/css/message.css" />
{% endblock %}

{% block js %}
    <script src="/static/js/message.js" type="text/javascript" charset="utf-8"></script>
{% endblock %}

{% block body %}
<div class="modal fade" id="send-message">
    <div class="modal-dialog">
        <form class="modal-content" id="send-message-form">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h3 class="modal-title text-center">Send Message</h3>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="head-img">选择头像</label>
                    <div class="dropdown" id="head-img">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">

                        <img src="/media/{{top_headImage.image}}" class="img-circle"/>
                        <input type="text" name="image" class="hidden" value="/media/{{top_headImage.image}}" />
                        </button>

                        <ul class="dropdown-menu text-center" aria-labelledby="dropdownMenu1">
                            {% for head_image in head_images %}
                            <li>
                                <img src="/media/{{head_image.image}}" class="img-circle center-block img-select" />
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">您的名字<span class="must-input">*必填</span></label>
                    <input type="text" id="username" placeholder="please input your name" class="form-control" name="username" />
                </div>
                <div class="form-group">
                    <label for="email">您的邮箱<span class="must-input">*必填(不公开)</span></label>
                    <input type="text" id="email" placeholder="please input your email" class="form-control" name="email" />
                </div>
                <div class="form-group">
                    <label for="username">您的网址<span class="select-input">&nbsp;选填</span></label>
                    <input type="text" id="address" placeholder="please input your address" class="form-control" name="address" />
                </div>
                <div class="form-group">
                    <label for="username">您的留言<span class="must-input">*必填</span></label>
                    <textarea id="message" name="message" rows="10" class="form-control" placeholder="please input your message"></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" id="close-btn">关闭</button>
                <button type="reset" class="btn btn-primary" id="reset-btn">重置</button>
                <button type="button" class="btn btn-primary" id="send-btn">发送</button>
            </div>

        </form>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="container">
    <div class="col-md-8 body-left">
        <div class="panel">
            <div class="panel-heading">
                <h1 class="text-center">Message</h1>
            </div>
            <div class="panel-body message-list">
                <button class="btn btn-primary center-block" type="button" data-target="#send-message" data-toggle="modal" id="send-message-btn">给&nbsp;我&nbsp;留&nbsp;言</button>
                <ul class="media-list">
                    {% for send_message in send_messages.object_list %}
                    <li class="media">

                        <div class="media-object col-md-2">
                            <img src="{{send_message.image}}" class="img-circle" />
                            <div class="triangle pull-right">
                            </div>
                        </div>
                        <div class="col-md-10 message-body">
                            <h3 class="media-heading">{{send_message.username}}:</h3>
                            <p>{{send_message.message}}</p>
                            <div class="media-bottom pull-right">
                                <h4>{{send_message.add_time}}</h4>
                            </div>
                        </div>

                    </li>
                   {% endfor %}
                </ul>
            </div>

            <div class="row text-center">
                <ul class="pagination">
                    {% if send_messages.has_previous %}
                    <li id="pre-page">
                        <a href="?{{send_messages.previous_page_number.querystring}}" aria-label="Previous">
                            <span aria-hidden="true">上一页</span>
                        </a>
                    </li>
                    {% endif %}

                    {% for page in send_messages.pages %}
                        {% if page == pre_ignore_page|add:1%}
                        <li class="pages">
                            <a href="?{% if not send_sort == 0 %}sort={{send_sort}}&{% endif %}id={{article.id}}&page={{pre_ignore_page}}">
                                ...
                            </a>
                        </li>
                        {% endif %}
                        {% if page %}
                        <li class="pages {% ifequal page send_messages.number %}active{% endifequal %}">
                            <a href="?{{page.querystring}}">{{page}}</a>
                        </li>
                        {% endif %}
                        {% if page|add:1 == next_ignore_page %}
                        <li class="pages">
                            <a href="?{% if not send_sort == 0 %}sort={{send_sort}}&{% endif %}id={{article.id}}&page={{next_ignore_page}}">
                                ...
                            </a>
                        </li>
                        {% endif %}
                    {% endfor %}

                    {% if send_messages.has_next %}
                    <li id="next-page">
                        <a href="?{{send_messages.next_page_number.querystring}}" aria-label="Next">
                            <span aria-hidden="true">下一页</span>
                        </a>
                    </li>
                    {% endif %}

                </ul>
            </div>

        </div>
    </div>
    <div class="col-md-4 body-right">
        <div class="jumbotron">
            <div class="panel">
                <div class="panel-heading">
                    <h3>Motto</h3>
                </div>
                <div class="panel-body">

                    <p class="motto">{{writings.content}}</p>
                    <footer class="pull-right">
                        <span>————</span>
                        {{writings.from_name}}
                    </footer>

                </div>
            </div>
            <div class="panel">
                <div class="panel-heading">
                    <h3>最新文章</h3>
                </div>
                <div class="panel-body">
                    <ul class="list-group panel-list">
                        {% for new_article in new_articles %}
                        <li class="list-group-item">
                            <a class="title" href="{% url 'articles_manage:article' %}?id={{new_article.id}}">
                                <span class="pull-left">{{new_article.name}}</span>
                                <span class="pull-right">{{new_article.add_time}}</span>
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="col-md-6 col-lg-push-3 text-center center-block alert-danger hidden">
    <h1>请填写好所有必填内容，谢谢!</h1>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
    $(function() {
        new MessageOperation("{% url 'operation:send_message' %}");
    });
</script>
{% endblock %}

templates/public.html
<!DOCTYPE html>
<html>

	<head>
		<meta charset=utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="keywords" content="{% block keywords %}{% endblock %} - 个人网站，博良个人博客,博良网站，博良博客,个人原创网站，博良，博良的BLOG, 博良的blog" >
		<meta name="Description" itemprop="description" content="{% block desc %}{% endblock %}博良的博客，分享学习知识，工作经验和生活,值得大家收藏的原创博客网站。" >
		<meta itemprop="name" content="{% block name %}{% endblock %}博良的博客，分享学习知识，工作经验和生活,值得大家收藏的原创博客网站。" />
		<meta name="author" content="博良" />
		<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no" />
		<title>{% block title %}public{% endblock %} - 博良的BLOG</title>

		<!-- Bootstrap -->
		<link href="/static/css/bootstrap.min.css" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="/static/css/public.css" />
		{% block css %}{% endblock %}
		<script src="/static/js/jquery-3.2.1.min.js" type="text/javascript" charset="utf-8"></script>
		<script src="/static/js/bootstrap.min.js" type="text/javascript" charset="utf-8"></script>
		{% block js %}{% endblock %}
		<!--[if It IE 8]>
    		<script>window.location.href = '{% url 'main:ie8' %}';</script>
    	<![endif]-->

		<!-- HTML5 shim and Respond./static/js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond./static/js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
      <script src="https://cdn.boot/static/css.com/html5shiv/3.7.3/html5shiv.min./static/js"></script>
      <script src="https://cdn.boot/static/css.com/respond./static/js/1.4.2/respond.min./static/js"></script>
    <![endif]-->

	</head>

<body>
<div class="main">
	<div class="container">
		<div class="top">
			<h1 class="text-center">博良的BLOG</h1>
		</div>
		<div class="navbar header">
			<div class="navbar-brand">
				BLOG
			</div>
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-btns" aria-expanded="false">
			 <span class="sr-only">Toggle navigation</span>
			 <span class="glyphicon glyphicon-th-list"></span>

		  </button>
			</div>

			<div class="navbar-collapse collapse" id="nav-btns">
				<ul class="navbar-nav nav">


					<li>
						<a href="{% url 'main:index' %}" class="{% if active == 'home' %}active{%endif%}">
							Home
						</a>
					</li>
					<li>
						<a href="{% url 'articles_manage:study' %}" class="{% if active == 'study' %}active{%endif%}">
							Study
						</a>
					</li>
					<li>
						<a href="{% url 'articles_manage:feelings' %}" class="{% if active == 'feelings' %}active{%endif%}">
							Feelings
						</a>
					</li>
					<li>
						<a href="{% url 'photos:photos' %}" class="{% if active == 'photos' %}active{%endif%}">
							Photos
						</a>
					</li>
					<li>
						<a href="{% url 'operation:message' %}" class="{% if active == 'message' %}active{%endif%}">
							Message
						</a>
					</li>
					<li>
						<a href="{% url 'about_me:about' %}" class="{% if active == 'about' %}active{%endif%}">
							About Me
						</a>
					</li>

				</ul>
			</div>

		</div>
	</div>

	{% block body %}{% endblock %}

	<div class="container footer">
		<h3>Design By 博良</h3>
	</div>
</div>
</body>
{% block script %}{% endblock %}

</html>